package akuto2.peex.utils;

import cpw.mods.fml.common.ModMetadata;

public class ModInfo {
	public static void load(ModMetadata meta) {
		meta.modId = "PEEX";
		meta.name = "PEEX";
		meta.description = "Final Form of Equipment to Produce EMC";
		meta.version = "1.2.6";
		meta.url = "https://minecraft.curseforge.com/projects/peex";
		meta.updateUrl = "";
		meta.authorList.add("akuto2");
		meta.autogenerated = false;
	}
}
