package akuto2.peex.utils;

import net.minecraftforge.fml.common.ModMetadata;

public class ModInfo {
	public static void registerInfo(ModMetadata metadata) {
		metadata.modId = "peex";
		metadata.name = "PEEX";
		metadata.description = "Final Form of Equipment to Produce EMC";
		metadata.version = "3.0.9";
		metadata.url = "https://www.curseforge.com/minecraft/mc-mods/peex";
		metadata.updateJSON = "https://raw.githubusercontent.com/akuto2/PEEX/master/PEEX-Update.json";
		metadata.authorList.add("akuto2");
		metadata.autogenerated = false;
	}
}
